services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    env_file:
      - .env
    command: >
      http --url=${NGROK_DOMAIN} 5678
    ports:
      - "5678:5678"

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    depends_on:
      - ngrok
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_RUNNERS_ENABLED=true
      - N8N_TRUST_PROXY_ENABLED=true

volumes:
  n8n_data: